config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :recommendations
  root to: 'home#index'
  # devise_scope :user do
  #   root to: 'users/sessions#new'
  # end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users
  post '/recommendations/vote', to: 'recommendations#vote'
  post '/stocks/follow', to: 'stocks#follow'
  # post '/stocks/unfollow', to: 'stocks#unfollow'
  get '/dashboards', to: 'dashboards#index'
  post '/subscribe', to: 'subscriptions#create'
  post '/push', to: 'push_notifications#create'
  get '/roles', to: 'roles#index'
  post '/roles/change_role', to: 'roles#change_role'

  resources :males, controller: 'users', type: 'Male'
  resources :females, controller: 'users', type: 'Female'

  namespace :api do
    namespace :v1 do
      resources :subscriptions, only: :create
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  acts_as_votable
  belongs_to :stock
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :set_recommendation, only: %i[show edit update destroy vote]

  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.includes(:stock).all
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
    @recommendation
  end

  # GET /recommendations/new
  def new
    @recommendation = Recommendation.new
    authorize @recommendation
  end

  # GET /recommendations/1/edit
  def edit
    authorize @recommendation
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    authorize Recommendation
    @recommendation = Recommendation.new(recommendation_params)
    @web_push_notification = WebPushNotification.new(title: @recommendation.title, body: @recommendation.description)
    respond_to do |format|
      if @recommendation.save && @web_push_notification.save
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully created.' }
        format.json { render :show, status: :created, location: @recommendation }
      else
        format.html { render :new }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    authorize @recommendation
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { render :show, status: :ok, location: @recommendation }
      else
        format.html { render :edit }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    authorize @recommendation
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url, notice: 'Recommendation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vote
    @recommendation.liked_by current_user
    render json: { recommendation: @recommendation, votes: @recommendation.votes_for.size }, status: :ok
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recommendation
    @recommendation = Recommendation.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recommendation_params
    params.require(:recommendation).permit(:title, :description, :stock_id)
  end
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_form.html.erb
<%= form_with(model: recommendation, local: true) do |form| %>
  <% if recommendation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recommendation.errors.count, "error") %> prohibited this recommendation from being saved:</h2>

      <ul>
      <% recommendation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :stock %>
    <%= form.select :stock_id ,Stock.all.collect {|s| [ s.title, s.id ] },{},class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :recommendation_title,class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :recommendation_description,class: "form-control"%>
  </div>
  <div class="actions">
    <%= form.submit "Submit",class: "btn btn-primary" %>
  </div>
<% end %>

app/views/recommendations/edit.html.erb
<div class="container">
  <h1>Editing Recommendation</h1>
  <%= render 'form', recommendation: @recommendation %>
  <%= link_to 'Show', @recommendation %> |
  <%= link_to 'Back', recommendations_path %>
</div>

app/views/recommendations/index.html.erb
<div class="container">
  <p id="notice"><%#= notice %></p>
  <h1>Recommendations</h1>
    <table class="table">
      <thead>
        <tr>
          <th>Stock Name</th>
          <th>Recommendation Title</th>
          <th>Description</th>
          <th>No Of votes</th>
          <th>Do Vote</th>
          <th>Show</th>
          <%if current_role != 'Viewer'%>
            <th colspan="2" class="text-center">Actions</th>
          <%end%>
        </tr>
      </thead>
      <tbody>
        <% @recommendations.each do |recommendation| %>
          <tr id="rec_<%=recommendation.id%>">
            <td><%= recommendation.stock.try(:title) %></td>
            <td><%= recommendation.title %></td>
            <td><%= recommendation.description %></td>
            <td class="vote"><%= recommendation.votes_for.size %></td>
            <td> <button type="button" class="btn btn-success" onclick="doVote(<%=recommendation.id%>)">
              <i class="fa fa-thumbs-up" aria-hidden="true"></i> Do Vote
        </button></td>
            <td><%= link_to 'Show', recommendation %></td>
            <%if current_role != 'Viewer'%>
              <td><%= link_to 'Edit', edit_recommendation_path(recommendation) %></td>
              <td><%= link_to 'Destroy', recommendation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
          </tr>
        <% end %>
      </tbody>
  </table>

  <br>
  <%if current_role != 'Viewer'%>
    <%= link_to 'New Recommendation', new_recommendation_path %>
  <%end%>
</div>

app/views/recommendations/new.html.erb
<div class="container">
  <h1>New Recommendation</h1>
  <%= render 'form', recommendation: @recommendation %>
  <%= link_to 'Back', recommendations_path %>
</div>

app/views/recommendations/show.html.erb
<div class="container">
  <p id="notice"><%#= notice %></p>
  <p>
    <strong>Title:</strong>
    <%= @recommendation.title %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= @recommendation.description %>
  </p>
  <p>
    <strong>No Of Votes:</strong>
    <%= @recommendation.votes_for.size %>
  </p>
  <%if current_role != 'Viewer'%>
      <%= link_to 'Edit', edit_recommendation_path(@recommendation) %> |
  <%end%>
  <%= link_to 'Back', recommendations_path %>
</div>