config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  resources :recommendations
  root to: 'home#index'
  # devise_scope :user do
  #   root to: 'users/sessions#new'
  # end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :users
  post '/recommendations/vote', to: 'recommendations#vote'
  post '/stocks/follow', to: 'stocks#follow'
  # post '/stocks/unfollow', to: 'stocks#unfollow'
  get '/dashboards', to: 'dashboards#index'
  post '/subscribe', to: 'subscriptions#create'
  post '/push', to: 'push_notifications#create'
  get '/roles', to: 'roles#index'
  post '/roles/change_role', to: 'roles#change_role'

  resources :males, controller: 'users', type: 'Male'
  resources :females, controller: 'users', type: 'Female'

  namespace :api do
    namespace :v1 do
      resources :subscriptions, only: :create
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>StackRecommendation</title>
		<%= csrf_meta_tags %>
		<link rel="manifest" href="/manifest.json" />

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>

		<nav class="navbar navbar-dark bg-dark">
			<a class="navbar-brand" href="/"><img class="logo" src="http://ec2-3-16-101-50.us-east-2.compute.amazonaws.com/crediwatch/wp-content/uploads/2019/07/logo-white.png"></a>
			<form class="form-inline">

				<%if current_user%>
					<div style="padding-left: 10px;">
						<%=link_to "Change Role",roles_path,class: "btn btn-outline-success"%>
					</div>
					<div style="padding-left: 10px;">
						<%#=link_to "Dashboards",dashboards_path,class: "btn btn-outline-success"%>
					</div>
					<%if current_user.is_admin?%>
						<div style="padding-left: 10px;">
							<%=link_to "Stocks",stocks_path,class: "btn btn-outline-success"%>
						</div>
						<div style="padding-left: 10px;">
							<%=link_to "Users",users_path,class: "btn btn-outline-success"%>
						</div>
					<%end%>
					<div style="padding-left: 10px;">
						<%=link_to "Recommendations",recommendations_path,class: "btn btn-outline-success"%>
					</div>
					<div style="padding-left: 10px;">
						<%=link_to "Logout",destroy_user_session_path,method: :delete,class: "btn btn-outline-danger"%>
					</div>
				<%else%>
					<div style="padding-left: 10px;">
							<%=link_to "Sign In",user_github_omniauth_authorize_path,class: "btn btn-outline-success"%>
					</div>
				<%end%>
			</form>
		</nav>
		<% flash.each do |key, value| %>
			<%key = key=='notice' ? 'primary': key%>
  		<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
	</body>
</html>